### ISSUE TITLE
uv.h should not leak implementation details

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#104]
Proposal:

```
#ifdef WANT_UV_INTERNALS

#include "c-ares.h"
#include "eio.h"

struct some_private_struct { /* */ };
void some_private_function(void);

#endif
```

**Comment by rmustacc** [comment]
Rather than having it hidden behind an ifdef why not just use a second header file like uv-impl.h which isn't installed?

**Comment by ry** [comment]
c-ares is public.

eio will be private once we do a file system API.

I would like very much to not leak ev.h, uv-win.h, and uv-unix.h but I don't see what can be done about it.

**Comment by dolmen** [comment]
@ry: I agree with @bnoordhuis and @rmustacc: there are too much implementation details available in `libuv.h`.

Here is an example: `uv_stream_t`.
This should be an opaque pointer for the user of the API, so the internal definition of the private members must not even appear in any files included (directly or indirectly) by the user of the API.
`libuv.h` should only contain the following line (no definition of `struct uv_stream_s` at all):

``` c
typedef struct uv_stream_s uv_stream_t;
```

The members of `uv_stream` will only be defined in a private include that you will store in the src dir and that will not be exposed to the API user.

By the way, the `typedef` could also include the '*'. One less char to type (and to forget to type) for the API users and that pollutes documentation (prototype). It keep the API explicitely more opaque to its implementation.
And you can also remove the '_s' suffix : structs have their own namespace and can only be used with the 'struct' keyword, so the _s is redundant.

``` c
typedef struct uv_stream *uv_stream_t;
```

Structures such as `uv_udp_send_s` that mix private and public members must also be completely rethinked. Only public members must be exposed in the API. Hidding them with macro is just a bad trick, and you'll not be able to preserve binary compatibility if you have to change the implementation.

More constistency also must be used in types names. Why uv_file doesn't have the "_t" suffix like others?

And types which are public structures that the user will have to allocate himself (usually on the stack) should preferably kept just as `struct uv_foo_bar` instead of `uv_foo_bar_t`.

**Comment by ry** [comment]
@dolmen, I appreciate your comments but exposing those structs and not hiding star are design goals - not problems. We expose the structs so users can manage their own memory. Typedeffing pointers IMHO makes code hard to read. We're not concerned with protecting users from private members - they can just read the docs.

**Comment by dolmen** [comment]
Beside binary compatibility that you do not seem to care about, private members exposed as you do are also exposed in debuggers. My point is that kind of information should be only available when debugging the API implementation, but not when debugging a client application.

**Comment by bnoordhuis** [comment]
Closing. uv.h is reasonably tidy now.
