### ISSUE TITLE
Building with Ninja fails

### ISSUE THREAD

**Issue by IngwiePhoenix** [joyent/libuv#1051]
When I try to build using ninja, it fails quite hard. See this one for more: http://puu.sh/5To4m.txt

**Comment by indutny** [comment]
Do you have the latest version of `ninja` installed, or the one provided by brew? I'm using ninja on OSX for all builds I do and it works perfectly.

**Comment by IngwiePhoenix** [comment]
I compiled it straight from Github - i dont like Brew. :I
Am 21.12.2013 um 09:44 schrieb Fedor Indutny notifications@github.com:

**Comment by indutny** [comment]
Do you have xcode command line tools installed?

**Comment by IngwiePhoenix** [comment]
I have actualyl three toolchains: Xcode, GNUstep(gcc 4.8.2 with objc support) and drag0n (a toolchain i built myself). All three have build various, if not all, packages I ever needed to compile.
Am 21.12.2013 um 17:52 schrieb Fedor Indutny notifications@github.com:

**Comment by indutny** [comment]
It looks like it tries to use `drag0n` toolchain and fails, honestly saying only xcode toolchain is supported on osx, since it is using a FSEvents and CoreServices.

Sorry, I may only suggest you figuring it yourself using options.gypi, something like this may make it work for you https://gist.github.com/indutny/c46ba8f770c1e553538f , where sdk_path could be obtained from: `xcodebuild -version -sdk macosx Path`, and sdk_dev_path from: `xcode-select -print-path`.
