### ISSUE TITLE
export UV_VERSION macro 

### ISSUE THREAD

**Issue by sukinull** [joyent/libuv#1111]
If API changes so dramatically version by version, is it possible to move
- UV_VERSION_MAJOR 
- UV_VERSION_MINOR 
- UV_VERSION_PATCH 
- UV_VERSION_IS_RELEASE 
- UV_VERSION 

to uv.h?

**Comment by saghul** [comment]
Nope, you should be using these: https://github.com/joyent/libuv/blob/master/include/uv.h#L231-L242

**Comment by retep998** [comment]
Knowing the version at runtime doesn't help with compiling the program in the first place, where a macro would be much more helpful to conditionally compile the correct calls.

**Comment by indutny** [comment]
@saghul indeed, we need to consider exporting them. Do you have any objections?

**Comment by saghul** [comment]
Hum, I hadn't considered that. I would definitely not export UV_VERSION_IS_RELEASE.

**Comment by indutny** [comment]
@saghul actually, it seems that this was intentionally removed from v0.11, because all patch versions have ABI compatibility.

**Comment by tjfontaine** [comment]
Patch versions may have ABI compatibility, but minor have significant API/ABI differences, and thus it's difficult to know against whom you're building, so you can't write code that targets two stables easily.

In Node it's not a problem because we do keep the same minor, but we also export useful macros.

A well behaved C library should definitely include version macros.

**Comment by indutny** [comment]
@saghul mind if I'll ask you help me with this? ;)

**Comment by saghul** [comment]
No problem, I'll make a patch.

**Comment by saghul** [comment]
Fixed in https://github.com/joyent/libuv/commit/d4c12adff648bc4ebd5038e8186069193b22a693
