### ISSUE TITLE
fs: make fd non-blocking before reading

### ISSUE THREAD

**Issue by indutny** [joyent/libuv#1126]
We should probably make all fds that we are trying to read from non-blocking and fail with `EWOULDBLOCK` or `EAGAIN` is returned. This way we could prevent users from passing character devices (like `/dev/tty`) to `uv_fs_read` and blocking the worker threads.

(Requires investigation).

**Comment by JohannesRudolph** [comment]
This is very interesting, can you elaborate on the consequences of the current libuv behavior when readin e.g. from a serial port? I'm asking because we're seeing some atrocious performance with fs.read from node.js which uses uv_fs_read under the covers (reading from /dev/ttyATH0 on an Arduino Yun).

See the discussion here for some performance numbers: https://github.com/voodootikigod/node-serialport/issues/402

All my knowledge of libuv is based on the guide and skimming the c code, but I thought that the main purpose of the threadpool used was to emulate async io using watchers and blocking a pool thread? 

In any case, with the current libuv we are not able to process a measly 12kB/s serial port (uses 100%CPU on that platform). Node --prof etc. also indicate most time is spent in libuv and libpthread (see test programs in the linked issue).

Is there something I could do to help land a fix for this?

**Comment by saghul** [comment]
We will have a specific handle for this: uv_devite_t, PR is still pending. Closing.

**Comment by JohannesRudolph** [comment]
Hi @saghul can you link the PR so we can track this?

**Comment by saghul** [comment]
@JohannesRudolph sure: https://github.com/joyent/libuv/pull/1580
