### ISSUE TITLE
remove rpcrt4 and ole32 libs from windows builds

### ISSUE THREAD

**Issue by igorzi** [joyent/libuv#118]

**Comment by DrPizza** [comment]
ole32 is easy to remove, of course, by calling `UuidCreate()` directly, but that doesn't really help with rpcrt4.

If you want to stick with GUIDs for random names, you could probably generate a version 4 UUID without any further lib dependencies (though you've probably got to wing it when it comes to the RNG, since the cryptographic RNGs mean trading one dependency for another). But a weak PRNG would probably be sufficient.

But you could probably just go for a much simpler scheme. Generate names like \.\pipe\uv\pid-random, and generate a new name if the call to `CreateNamedPipeA()` errors with `ERROR_ACCESS_DENIED`. `FILE_FLAG_FIRST_PIPE_INSTANCE` will reject any attempt to create a pipe with a pre-existing name, so there's no risk of accidentally opening someone else's pipe.

**Comment by igorzi** [comment]
we're thinking of doing _snprintf(name, size, "\\.\pipe\uv\%d-%p", pid, handle)

**Comment by DrPizza** [comment]
That would mean setting the name of the pipe only after you've created it, no?

**Comment by ry** [comment]
please remove https://github.com/joyent/node/blob/f0f941a59e42a22771583da55d78e454a58eb051/wscript#L496-499 when this bug is fixed and landed inside node

**Comment by igorzi** [comment]
@DrPizza: no, the handle here refers to uv handle (not windows handle).

**Comment by DrPizza** [comment]
Oh, of course. I didn't think that was normally safe (client code can stack allocate uv_pipe_ts) but I guess since `uv_process_options_t` stores only pointers then they'll tend to be created on the heap, so the addresses will all be unique.

**Comment by igorzi** [comment]
fixed with 6d940a3afcbd4280801f9adfb72c821c4edbccf9
