### ISSUE TITLE
pipe server locking in unix

### ISSUE THREAD

**Issue by ry** [joyent/libuv#124]
removed flock due to solaris incompatibilities https://github.com/joyent/libuv/commit/b2ed24d86ecc561135edf566878b43d93e364d44

please do this without `.lock` file or allocations if possible

**Comment by piscisaureus** [comment]
@ryah @bnoordhuis Is this issue still valid?

**Comment by bacchusrx** [comment]
The corresponding test still fails (current master on Darwin):

```
[%   0|+  38|-   1]: pipe_bind_error_addrinuse
`pipe_bind_error_addrinuse` failed: exit code 6
Output from process `pipe_bind_error_addrinuse`:
Assertion failed in test/test-pipe-bind-error.c on line 56: r == -1
=============================================================
```

In #158 I asked if it would be acceptable for now to get this working on non-Solaris platforms, using flock and #ifdef. At least then it's not broken everywhere. If so, I can put a pull request together, since I have this working again in my own fork (https://github.com/bacchusrx/libuv/compare/v0.6...pipe-flock-v0.6). If not, I don't have Solaris to test alternatives on.

However it's done, it'd be nice to get this fixed.

**Comment by bnoordhuis** [comment]
@piscisaureus: It's still broken.

@bacchusrx: I appreciate the offer but if it's broken (which it is) it should be _really_ broken as a not so gentle reminder to fix it.

**Comment by bnoordhuis** [comment]
Closing. Locking can't be implemented in a cross-platform way.
