### ISSUE TITLE
API for listening, but not executing events

### ISSUE THREAD

**Issue by kkaefer** [joyent/libuv#1246]
Multiple event loops can be integrated by using `uv_run(..., UV_RUN_ONCE)` or `uv_run(..., UV_RUN_NOWAIT)`. However, there are situations where the other event loop is sleeping (=waiting for other events), but libuv's event loop has something to execute. This doesn't get executed until the other event loop wakes up and calls `uv_run(..., UV_RUN_NOWAIT/ONCE)`.

Currently, we have [`uv_backend_fd()`](https://github.com/joyent/libuv/blob/d86d86633e5f7ff07cd94d31a495ec6bef619aa1/include/uv.h#L350-L364) which can be used as shown in https://github.com/joyent/libuv/blob/master/test/test-embed.c#L96: create another thread that _listens_ to the event loop's file descriptor (linux/unix only), but does not _execute_ any of the callback: Basically, the `embed_thread_runner` loop sleeps until there are events in the libuv event loop we want to embed another event loop. Once we know there are new events for our event loop, we can wake up the other event loop with event-loop/platform specific calls, to ensure that our libuv events are executed in the main thread as soon as we get them and don't wait until the other event loop happens to wake up.

I propose an API that does what https://github.com/joyent/libuv/blob/master/test/test-embed.c#L71-L86 does, but in a platform-agnostic way, something like `uv_run(..., UV_RUN_ONCE_NOCALLBACK)`, which does exactly what `UV_RUN_ONCE` does, but only blocks for IO/events rather than actually executed the event handlers.

This API is useful for e.g. integrating a libuv event loop in a GLFW/`glfwWaitEvents()` call. In the event listener thread, we wait for new events (but don't execute them!), then call glfwPostEmptyEvent() to wake up/interrupt GLFW's `glfwWaitEvents`.

**Comment by saghul** [comment]
Hi,

As discussed on IRC, I agree we need to make loop embedding easier, but but I don't quite like the idea of `UV_RUN_ONCE_NOCALLBACK`. Here is my proposal instead:

Have a `void uv_backend_poll(uv_loop_t* loop, int timeout)` function which would poll for i/o for the given timeout (only once even if -1 was specified) and queues the i/o events instead of firing callbacks.

Example usage:

```
loop = uv_default_loop();
// do this in an auxiliary thread
uv_backend_poll(loop, uv_backend_timeout(loop));
// signal the main thread when the polling is done
// uv_sem_post(...)
// run the loop in the main thread without blocking for i/o
uv_run(loop, UV_RUN_NOWAIT);
```

Now, the implementatio details:
- The Windows side seems less trouble because i/o operations are already queued and are ran at the begining of the loop iteration (`uv_process_reqs`). Just by running the poll function would be enough.
- On Unix it's a bit more complex: instead of calling the callbacks, we'd need to make the io handles pending, like `uv__io_feed` does, but for both `UV__POLLIN` and `UV__POLLOUT`. Right now, `uv__run_pending` only considers `UV__POLLOUT`. So we'd neeed to add another queue or some pending events field, and get the event type on `uv__io_feed`. Then `uv__io_poll` would need to get some `queue_events` parameter indicating if we want events to be queued or not.
- We'd also need to make `uv_backend_timeout` work on Windows, which is straightforward.

Calling the cavalry: @indutny, @piscisaureus (@bnoordhuis, it would be great to have your input on this one)

Thoughts?

**Comment by kkaefer** [comment]
I created a small sample app: https://github.com/kkaefer/gluv

You'll see that the current method of waiting for events with kqueue doesn't work; the `kevent` callback returns immediately and restarts the event loop. Currently, the callback is called about 60 times per second because `glfwSwapBuffers` waits until the next screen vsync to limit the frame rate.

**Comment by indutny** [comment]
@saghul I'm fine with it, I think it was present in initial implementation, before @bnoordhuis scissored it out ;)

**Comment by bnoordhuis** [comment]
Correct me if I'm wrong but uv_backend_poll() + uv_run() sounds like a half-baked pull implementation.  You may as well go the whole nine yards and implement a true uv_pull().

uv_poll() is arguably a better name but it might confuse people because of uv_poll_init(), uv_poll_start(), etc.

**Comment by saghul** [comment]
> Correct me if I'm wrong but uv_backend_poll() + uv_run() sounds like a half-baked pull implementation. You may as well go the whole nine yards and implement a true uv_pull().

Hi Ben, thanks for the feedback! The use case I'm trying to enhance here is the loop embedding. So, in this scenario, uv_backend_poll runs in an auxiliary thread, and when it's done it signals the main thread, which calls uv_run. This way the callbacks are run on the main app thread, but we didn't block it while polling.

That said, can you elaborate a bit (maybe some pseudocode would help) on what uv_pull would do? At first I thought you meant doing uv_backend_poll + uv_run (NOWAIT) in a single shot, but that would block the calling thread. I might be missing an important use case here.

Thanks!

**Comment by bnoordhuis** [comment]
Libuv uses a push model: you call uv_run() and uv_run() in turn calls your callbacks, i.e. it pushes events to you.

The pull model is essentially what poll(2) does: you tell the producer (the kernel in case of poll(), libuv in the hypothetical case of uv_pull()) to give you a list of pending events and then you, the consumer, can process those at your leisure.

In hindsight, we should've made libuv default to pull instead of push (one of my few major regrets) because it makes integration with other event loops much easier and because it's trivial to emulate push using pull but not the other way around.

uv_read_start() and uv_read_stop() complicate the issue somewhat; they're handle operations whereas (again, in hindsight) they should have been request-based.

In practice though it often already turns out that way.  Most non-trivial libuv applications that I've seen build an ad hoc request-based protocol (in the formalistic sense) on top of the read stream, usually expressed as a state machine that starts and stops reading.  See the SOCKS proxy sample app, for example.

That achieves the same thing as request-based read operations, only it's a lot more cumbersome.

**Comment by bnoordhuis** [comment]
> uv_read_start() and uv_read_stop() complicate the issue somewhat; they're handle operations whereas (again, in hindsight) they should have been request-based.

Forgot to add, uv-win internally already uses a request model for reads.  It then maps those back to per-handle operations.

**Comment by saghul** [comment]
> Libuv uses a push model: you call uv_run() and uv_run() in turn calls your callbacks, i.e. it pushes events to you.
> 
> The pull model is essentially what poll(2) does: you tell the producer (the kernel in case of poll(), libuv in the hypothetical case of uv_pull()) to give you a list of pending events and then you, the consumer, can process those at your leisure.

I see where you are getting at now. I had a very similar discussion with a nice Dutch guy who enjoys Windows ;-) 

> In hindsight, we should've made libuv default to pull instead of push (one of my few major regrets) because it makes integration with other event loops much easier and because it's trivial to emulate push using pull but not the other way around.

Yeah, if the guts are pull we could still have uv_run do what it currently does, but pulling the events and processing them automatically.

> uv_read_start() and uv_read_stop() complicate the issue somewhat; they're handle operations whereas (again, in hindsight) they should have been request-based.

And turn that into a uv_read(req) function that would specify the size to be read, I guess.

> In practice though it often already turns out that way. Most non-trivial libuv applications that I've seen build an ad hoc request-based protocol (in the formalistic sense) on top of the read stream, usually expressed as a state machine that starts and stops reading. See the SOCKS proxy sample app, for example.
> 
> That achieves the same thing as request-based read operations, only it's a lot more cumbersome.

Thanks for the detailed response Ben, this is very helpful. I'd like libuv to walk those 9 yards, I guess we need a plan for this. I'm still undecided if uv_backend_poll is a good thing to have with the current model, at least until we make deeper changes.

I guess that 10+ hour flight next week will help me think about this :-)

**Comment by saghul** [comment]
Closing, please follow this discussion: https://github.com/libuv/libuv/issues/6
