### ISSUE TITLE
SIGPIPE just prevented in OSX/BSD

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#1254]
I've realized that when libuv sets SO_NOSIGPIPE (when available) to prevent the case in which the socket tries to write to a connection reset by the peer so it would send a SIGPIPE signal to the process (which usually terminates the process unless it ignores it):

```

src/unix/core.c
365:#if defined(SO_NOSIGPIPE)
368:    setsockopt(sockfd, SOL_SOCKET, SO_NOSIGPIPE, &on, sizeof(on));
```

In Linux there is no SO_NOSIGPIPE (at least in Debian 7 with kernel Linux 3.2.0). The way to avoid SIGPIPE in Linux seems to be in the `send()` call adding a [MSG_NOSIGNAL flag](http://linux.die.net/man/2/send):

```
sendmsg(..., MSG_NOSIGNAL)
```

So, I'm not sure whether libuv should prevent SIGPIPE or not, but it should do it (or not) in all the OS.

What about adding MSG_NOSIGNAL in `sendmsg()`?

**Comment by saghul** [comment]
MSG_NOSIGNAL is supported in Linux 2.2+ which should be fine :-) However neither (MSG_NOSIGNAL, SO_NOSIGPIPE) are supported in Solaris. _Sigh_.

Maybe we should just do nothing and the user should set the signal handler to SIG_IGN. Thoughts @indutny? Also @bnoordhuis, since he added the code ;-)

**Comment by bnoordhuis** [comment]
The reason libuv doesn't use MSG_NOSIGNAL is that sendmsg() is a much more expensive system call than write().  I don't recall the exact numbers but it was on the order of 20% or more.

**Comment by indutny** [comment]
I believe @bnoordhuis ;)

**Comment by saghul** [comment]
I believe him too, but we might need to document this somewhere (where?!). OSX / BSD users don't need to worry about it but the rest do.

**Comment by ibc** [comment]
Honestly I don't understand the purpose of SIGPIPE. It is like telling a process "ey, some of your N sockets has tried to write into a connection reset by the peer". Ok, which socket? Haven't we already write error codes for that?

BTW I agree with @saghul. If non OSX/BSD users must deal with it it should be documented.

**Comment by sam-github** [comment]
SIGPIPE is so dumb apps, that call printf() to write to network (when was
the last time you saw someone check the return value of printf?), probably
because they are spawned by inetd, or else that are apps in shell pipelines
or some other scenario where they don't know stdio is redirected to a
socket, get killed with prejudice when they write to a closed connection.
Dumb apps.

Smart apps that explicitly create network connections in their own code,
like ones using libuv, are supposed to do the right thing and ignore
SIGPIPE as an explicit declaration to the OS that they intend to handle
errors themselves.

But problem arises, in that libuv should probably not ignore SIGPIPE
itself, its too opinionated to change global process state, so it just has
to make really clear in its docs that all network apps should ignore
SIGPIPE in their application setup.

Or perhaps the libuv loop init call should have a flag, that defaults to
"ignore SIGPIPE", so applications like node can do their own thing, but if
they don't set the flag saying "this app will ignore SIGPIPE itself" libuv
ignores it for them and they have no basis to complain about that.

​

**Comment by sam-github** [comment]
And maybe SO_NOSIGPIPE should not be set on any platform, if it
introduces unnecessary platform differences. Everybody should write
their code on Linux, anyhow (Sam ducks).

**Comment by ibc** [comment]
@saghul do you mean code like [this](http://bit.ly/1hpZNeI)? XD

**Comment by saghul** [comment]
> And maybe SO_NOSIGPIPE should not be set on any platform, if it introduces unnecessary platform differences.

Agreed.

**Comment by bnoordhuis** [comment]
There is a reason to keep SO_NOSIGPIPE around: performance.

Some applications will want to install a SIGPIPE handler to deal with signals generated outside of libuv.  If SO_NOSIGPIPE is not set, then signals from libuv will keep waking up the handler even though the signals are irrelevant.
