### ISSUE TITLE
linux: barrier test failure

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#1340]
I occasionally see this:

```
`barrier_3` failed: exit code 134
Output from process `barrier_3`:
Assertion failed in ../test/test-barrier.c on line 46: c->main_barrier_wait_rval == 0
```

@bnoordhuis any idea? I think it might be related to your last change regarding barrier_wait return code.

**Comment by bnoordhuis** [comment]
That's probably because of 6c6c922.  Looking at it again, there is a race window between the return from uv_barrier_wait() and the store to main_barrier_wait_rval or worker_barrier_wait_rval.

("return from uv_barrier_wait()" should be read as "the completion of the low-level sync primitive inside pthread_barrier_wait()" but that's rather a mouthful.)

**Comment by saghul** [comment]
Hum, test also fails on SunOS consistently. Do you suggest reverting?

**Comment by bnoordhuis** [comment]
Yes, that's probably best / easiest.
