### ISSUE TITLE
[feature request] cancel write requests

### ISSUE THREAD

**Issue by kazuho** [joyent/libuv#1393]
Is there any possibility that libuv would provide an interface to cancel write requests?

My understanding is that [RFC 6429](http://tools.ietf.org/html/rfc6429) suggests applications to close stalled connections to avoid DoS attacks, quote:

> A clever application needs to detect such attacks with connections that are not making progress, and could close these connections.

However, it is impossible to close a connection with an on-going write request unless there is a way to cancel the request.

My understanding is that it is per design that libuv does _not_ provide an interface for cancelling write requests ([source](https://www.mail-archive.com/libuv@googlegroups.com/msg00473.html)), but it would be great if you could reconsider.

**Comment by saghul** [comment]
> However, it is impossible to close a connection with an on-going write request unless there is a way to cancel the request.

You can just call `uv_close` on a TCP handle and the connection will be closed an all outstanding write requests will be canceled (callbacks will be called with UV_ECANCELLED). You cannot cancel an individual write request at the moment, though.

> My understanding is that it is per design that libuv does not provide an interface for cancelling write requests (source), but it would be great if you could reconsider.

That's not correct. The fact that we don't provide one right now it's not by design, it's just that no one found the time to do it. If you would like to see it done feel free to work on a PR extending `uv_cancel` to also cancel write requests. On Unix it should be pretty straightforward, not so much on Windows, though.

**Comment by kazuho** [comment]
Thank you for the answer!

I will try calling `uv_close` from a timeout callback.
