### ISSUE TITLE
UDP memory leaking when sending to inactive local port on Windows

### ISSUE THREAD

**Issue by k0dek0mmand0** [joyent/libuv#1426]
I'm using libuv version shipped with node 0.10.30 on Windows platform.

I think there's a problem with the UDP implementation, similar to the one discussed in issue #1194

If a datagram is sent from 127.0.0.1:10000 to 127.0.0.1:12345 and no-one is listening on port 12345, an alloc callback is triggered on the sending handle, but the allocated memory is never used anywhere (no read callback comes with this pointer).

I'm assuming an ICMP error message (destination unreachable?) is being received, but not handled.

If I add a listener on port 12345 (e.g. ffplay), everything works as advertised.

Here's some c++ code to reproduce the issue. In the output on my machine I see 10x SENT (status 0), followed by 10x ALLOC, then nothing else. Startup code not included.

``` c++
void _readCb(uv_udp_t*, ssize_t, uv_buf_t buf, struct sockaddr*, unsigned)
{
   printf( "READ %p\n", buf.base );
   free( buf.base );
}

uv_buf_t _allocCb(uv_handle_t*, size_t size)
{
   char* ptr = (char*)malloc( size );
   //
   printf( "ALLOC %p\n", ptr );
   //
   return uv_buf_init( ptr, (unsigned)size );
}

void _sendCb(uv_udp_send_t* req, int)
{
   printf( "SENT %p\n", req->data );
   free( req->data );
   free( req );
}

void testCase()
{
   uv_udp_t* h = (uv_udp_t*)malloc( sizeof( uv_udp_t ) );
   //
   sockaddr_in addrSrc = uv_ip4_addr( "127.0.0.1", 10000 );
   sockaddr_in addrDst = uv_ip4_addr( "127.0.0.1", 12345 );
   //
   uv_udp_init( uv_default_loop(), h );
   uv_udp_bind( h, addrSrc, 0 );
   uv_udp_recv_start( h, _allocCb, _readCb );
   //
   for( int i = 0; i < 10; i++ )
   {
      uv_buf_t buf = uv_buf_init( (char*)malloc( 10 ), 10 );
      //
      uv_udp_send_t *req = (uv_udp_send_t*)malloc( sizeof( uv_udp_send_t ) );
      //
      req->data = buf.base;
      //
      uv_udp_send( req, h, &buf, 1, addrDst, _sendCb );
   }
}
```

**Comment by saghul** [comment]
Can you make this a proper libuv test case?

To keep things in context, here is what I mentioned on #1194: "I checked the code on the Windows side and I only see one possible code path leading there: a WSAECONNRESET or WSAENETRESET error here: https://github.com/joyent/libuv/blob/master/src/win/udp.c#L508. alloc_cb was called but recv_cb won't be. This was introduced here: ea63f06"

**Comment by k0dek0mmand0** [comment]
I've made a [gist](https://gist.github.com/k0dek0mmand0/de162881912f9ce61c71) with the test case. Hope it helps.

**Comment by saghul** [comment]
It definitely does, thanks!

**Comment by saghul** [comment]
Hey @k0dek0mmand0, can you check #1441? Basically the buffer will now be returned the same way as Unix does when it get EAGAIN: with nread == 0 and addr == NULL.

**Comment by PowerSurge1** [comment]
Question about the fix - why not put the WSAECONNRESET error through uv_translate_sys_error? before passing it off to recv_cb? I see that it would already map to UV_ECONNRESET in those cases, and client code would probably be interested in getting that instead of just a zero. If it's a compatibility error with higher level code, we could consider adding another flag to enable that.

We could also consider folding the WSAECONNRESET and WSAENETRESET cases in with WSAEWOULDBLOCK, since the handling code is the same, and comments are the only difference.

**Comment by saghul** [comment]
This is quite peculiar use case of ECONNRESET. Basically what happens is that a previous UDP send failed, but because there is no way to report the error to the user, Windows makes the socket readable and reports that error. IIRC some Unixes also do it. The handling is the same as EAGAIN, in that we just need to return the buffer. The reason for handling it specifically like this is so we know why we are doing it, as this might come as a surprise.

**Comment by PowerSurge1** [comment]
Keeping the cases separate make sense.

How about giving the converted error code to the recv_cb? Maybe user code wants to know it's sending packets someplace bogus. I suppose a zero length read could be a signal that something bad happened...

Thanks for your quick response, by the way :)

**Comment by saghul** [comment]
@PowerSurge1 My pleasure :-) Getting such an error there means there was an error in a _send_ request, so it's irrelevant, confusing and not cross-platform. I don't see any good reason to do it.

**Comment by PowerSurge1** [comment]
Thank you.
