### ISSUE TITLE
add uv_fs_scandir

### ISSUE THREAD

**Issue by tjfontaine** [joyent/libuv#1431]
With the advent of `uv_fs_readdir` we should provide a migration path for old code who rely on the old behavior and add `uv_fs_scandir`

**Comment by saghul** [comment]
I don't mind renaming these before 1.0.0, I'd say we are still on time. `uv_fs_readdir_next` happened in 0.11, so we could just go ahead and rename them to `uv_fs_scandir` and `uv_fs_scandir_next`.

Then we can think about readdir, which is a tad different, because every time you want the next entry we need to do a roundtrip through the threadpool, so it will need a callback interface.

Thoughts, @indutny?

**Comment by indutny** [comment]
I'm +1 for it.

**Comment by tjfontaine** [comment]
We don't always need to round trip for readdir, we would do it roughly the same as the rest of the FS mechanism, such that we have an async and sync, then we could chunk up say reading 32 dirents at a time for each loop, but at least it's at the discretion of the user

**Comment by saghul** [comment]
> We don't always need to round trip for readdir, we would do it roughly the same as the rest of the FS mechanism, such that we have an async and sync, then we could chunk up say reading 32 dirents at a time for each loop, but at least it's at the discretion of the user

Yes, I had something like that in mind. Let's discuss those on #1430 though.

For this one, are you also OK with renaming then?

**Comment by tjfontaine** [comment]
yup

**Comment by saghul** [comment]
#1496 landed, closing.
