### ISSUE TITLE
Handle case when O_NONBLOCK != SOCK_NONBLOCK

### ISSUE THREAD

**Issue by saghul** [joyent/libuv#1442]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=759673

**Comment by lucab** [comment]
Patch attached to the bug report, available at https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=5;filename=libuv.hppa.patch;att=1;bug=759673

**Comment by bnoordhuis** [comment]
The patch looks reasonable to me. @lucab Can you file it as a PR at https://github.com/libuv/libuv?  I don't want to take it as-is because then it won't have proper attribution in the commit history.

Aside, I think we can safely drop the `UV__O_NONBLOCK` define.  I may have been overly cautious with that one.

**Comment by lucab** [comment]
I am not the original author. I already asked the OP to fill a PR here in reply to the debian bug report, but it looks like he is not following up.
I can cook a commit in his name, if you want.

**Comment by bnoordhuis** [comment]
@lucab Yes please, that would be great.

EDIT: I see you beat me by 37 seconds.  Thanks. :-)

**Comment by lucab** [comment]
Telepathy :)
It should probably be propagated across all the branches (master, v1.x, v0.10) though.

**Comment by saghul** [comment]
Thanks guys, closing!

**Comment by bnoordhuis** [comment]
@lucab Yes, we'll up-merge it around release time (unless you have a pressing need for it now.  If so, just holler.)
