### ISSUE TITLE
windows: cannot retrieve corresponding handle from fd opened by libuv

### ISSUE THREAD

**Issue by mscdex** [joyent/libuv#1493]
I recently ran into an issue where `_get_osfhandle()` would fail on Windows with an fd (e.g. 3) that came from node/libuv (via `fs.openSync()` for example). When I compile the binding using these Windows APIs, I am seeing a debug assertion from the VC++ library: Expression: (_osfile(fh) & FOPEN)

As far as i can tell libuv still uses `_open_osfhandle()` on Windows, whose return value should be compatible with `_get_osfhandle()`.

The reason for all of this in the first place is that I was trying to get `lseek()` and similar APIs to work so that I could retrieve the current position in an opened file. That way if I were to open a file for appending, I could know at what position I started writing bytes to without having to call `stat()`. Maybe there's a better way to do this even?

**Comment by saghul** [comment]
That's really weird. We already use `_get_osfhandle` on `uv_fs_read` and `uv_fs_write` for example. Do you have a test case I could try out?

**Comment by mscdex** [comment]
[Here](https://gist.github.com/mscdex/5a69b5960a876ba21873) is the code I'm using.

**Comment by saghul** [comment]
How can I compile your test case on Windows? (don't tell anyone, but I have never compiled a Node binary addon on The Redmond OS).

**Comment by mscdex** [comment]
Just `node-gyp rebuild` for release build and `node-gyp -d rebuild` for debug build. If you don't already have it installed globally, you will need to do `npm install node-gyp -g` first.

**Comment by moteus** [comment]
Hello. I had same problem.
The reason in my case was is I use static version of MSVCRT. Each instance has its own version of fd set. So same fd in two modules could have different handles and point to different files. The solution is using same dynamic version of runtime library. But I do not how it is implemented in mingw.

**Comment by piscisaureus** [comment]
The msvcrt double-linking problem is known and unfortunately I can't think of an easy solution for it.

A stop-gap solution could be to expose `uv_os_handle_from_fd()`, but that would only work as a replacement for `_get_osfhandle` and not for any other api that takes an fd (like `lseek`). So maybe not that useful.

Long-term, we would have to make libuv capable of everything msvcrt can do; but that's a far way out.
It would be nice, especially for windows users, because the i/o routines that msvcrt implements are almost all broken in some way.

I'll close this issue for now; if anyone has a good idea about how to fix it, a new issue or pull request would be very welcome.

**Comment by jorangreef** [comment]
Is there any change on this?

See: https://github.com/nodejs/nan/issues/671
