### ISSUE TITLE
handle->write_queue_size >= req->queued_bytes

### ISSUE THREAD

**Issue by zhs077** [joyent/libuv#1583]
发送50KB就会出现这种错误？？？

**Comment by JacksonTian** [comment]
Maybe you should give detail, such as stack.

**Comment by saghul** [comment]
Also, please use English so we can help you better.

**Comment by xzzh999** [comment]
I had the same problem before(我也曾出现过这个错误), but when you send data in the loop thread, that would not happen again(但是只要你保证发送的调用和主循环在同一个线程中,就不会有这个问题).
Also you should always use the stable version(同时你也应该尽量使用stable版本).  Otherwise its could cause some strange crash or bad stack errors(否则会导致一些奇怪的崩溃问题或者堆栈错误问题).

Look the follow link or search reference links like it:(查看下面的链接或者搜索相关的链接)
     https://github.com/joyent/libuv/issues/1409

**Comment by saghul** [comment]
Sorry, there is not enough data to debug this issue. If you think you founf one, please open a new issue with a libuv test case showing it so we can debug it. Also, #1409 was not a libuv issue since it's not thread safe to write to a stream from a different thread.
