### ISSUE TITLE
uv_queue_work should manage its own request

### ISSUE THREAD

**Issue by defunctzombie** [joyent/libuv#261]
Currently, when calling uv_queue_work you have to provide the uv_work_t object and then clean it up after you use it. This is very error prone. It would be nice to adopt libeio behavior here and just have the user provide the baton pointer. The library should handle the creation of the work_t and destruction of it.

Thoughts? I am happy to provide the patch if this is the way forward.

**Comment by bnoordhuis** [comment]
No, for two reasons:
1. One of libuv's design goals is to do as little malloc'ing as possible. That's why the caller is responsible for and has ownership of the uv_work_t struct.
2. The uv_work_t struct is embeddable and that makes it very convenient to look up the embedding struct in your callback with a container_of construct ([example](https://github.com/joyent/node/blob/216019b/src/node_crypto.cc#L4172)). It's also a much more robust technique than pointer indirection since there is no risk of dangling pointers.

**Comment by defunctzombie** [comment]
The issue I see is that you _have_ to have a uv_work_t struct and that you have to clean it up right after you use it, not at any other time. Why does it matter that you can embed it? Each of the callbacks (during and after) all receive a pointer to it. The point is that in lib eio the library stored it for you because it was a detail of the inner workings that the end user does not really care about. I just want to manage my baton pointer and not have to worry about handling the memory for other parts of the systems.

I would understand not wanting to do the memory management if the use of the uv_work_t struct was more free form, but this is not the case since you need one to queue work and have no use for it after you are done with the work. All it does it provide another point of error (and in this case potential leaks) for the user of the library.
