### ISSUE TITLE
check that echo_server doesn't return non-zero during ping_pong test

### ISSUE THREAD

**Issue by ry** [joyent/libuv#3]
test-runner bug - it should fail if a helper fails.
@gissues:{"order":75,"status":"backlog"}

**Comment by piscisaureus** [comment]
Then there needs to be a way to gracefully shutdown echo_server.

**Comment by ry** [comment]
not necessarily- you can use the process_wait with a small timeout on each of the helpers after the main process exits. if process_wait has not timed out then kill the helper and assume everything is fine.

**Comment by ry** [comment]
sorry - above was accidentally pushed. it's not in the history any longer

**Comment by ry** [comment]
something like this https://gist.github.com/925116 would catch crash errors from echo_server

**Comment by piscisaureus** [comment]
Looks good. 
- should we change process_wait to not take a vector? We're not using it anyway.
- Is the race condition intentional? During `if (timeout) {terminate(); wait();}` the process can still exit gracefully. But if that happens the timeouts in are probably wrong, so it's good that ASSERT(result != 0); fails.

**Comment by ry** [comment]
let's keep the vector. i'll land this once i figure out how to wait with timeouts in unix - it's not so easy.

**Comment by saghul** [comment]
Closing old stalled issues, please reopen at https://github.com/libuv/libuv if still needed.
