### ISSUE TITLE
remove some of these unnecessary status codes and int return values

### ISSUE THREAD

**Issue by ry** [joyent/libuv#40]
e.g on the uv_loop_cb

what else?

**Comment by piscisaureus** [comment]
uv_async_cb has the same useless status code.

On windows uv_prepare|check|idle|timer_init can never fail, I don't know about unix.

On windows ev_timer_start can fail if the btree is in inconsistent state. However I kill the loop if that happens, because it would probably mean that there is a bug in libuv or the user specified a nonexisting handle.

We need to think about what checks uv functions do. E.g. do they check if the handle type is correct, do they check if the handle isn't closing, do they check if the socket is connected when doing a read, does it check whether a req is improperly reused?

**Comment by saghul** [comment]
#1190 landed, closing... :-)
