### ISSUE TITLE
Does UV iterates when a signal is received?

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#418]
Hi, using UV (Linux) master branch, I've realized that when the process is blocked in uv_run (i.e. a single timer to expire in 200 seconds), if a system signal arrives (INT/QUIT/TERM/USR1...) uv_run iterates so callbacks prepare and check handles are executed.

I don't remember this behavior in previous versions. Is this the expected behavior?

**Comment by bnoordhuis** [comment]
> I don't remember this behavior in previous versions. Is this the expected behavior?

Yes. Though I might change that if it turns out to be troublesome.

**Comment by ibc** [comment]
And, would it better if upon receipt of a signal UV calls a specific callback?:

```
typedef void (*uv_signal_received_cb)(int signal);
```

**Comment by bnoordhuis** [comment]
> And, would it better if upon receipt of a signal UV calls a specific callback?:

No, for two reasons:
1. Signals are platform-specific (they're a very UNIX-y thing), hence libuv will never expose them directly.
2. libuv doesn't actually catch signals (except SIGCHILD and only if you create child processes) so there's nothing to pass on. What happens is that the signal interrupts the `epoll_wait()` / `kevent()` / etc. syscall, that's why the prepare and check handlers run.

**Comment by ibc** [comment]
Clear. Thanks a lot.
