### ISSUE TITLE
Can tcp_connect_cb() be called after uv_tcp_t has been uv_closed and freed?

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#433]
(Linux)

I'm experimenting some errors in my code. They occur when I close a `uv_tcp_t` handle while it was in "connecting" status (to a remote server). What I see is:
1. I close the handle: `uv_close(handle, close_cb)`.
2. I "think" (not sure yet) that `close_cb` (which frees the handle) is executed now or in next iteration, you know.
3. I get my `tcp_connect_cb()`called in which I get the `uv_connect_t* req`. From `req` I can get the handle via `req->handle`.

I wonder if step 2 could occur before step 3, so that means that accesing to `req->handle` would get a freed pointer. Am I wrong?

Thanks a lot.

**Comment by bnoordhuis** [comment]
libuv guarantees that all request callbacks (connect, write, shutdown, etc.) run before the handle is closed. Between the call to `uv_close()` and the call to `close_cb`, your connect callback gets called.

`connect_req->handle` is still valid at that point because you're not supposed to free the handle's memory until `close_cb` is called.

**Comment by ibc** [comment]
Thanks a lot. It's clear.
