### ISSUE TITLE
" getting 1/3 sys usage and 5x throughput with custom batching"

### ISSUE THREAD

**Issue by ry** [joyent/libuv#496]
https://twitter.com/tjholowaychuk/status/224399224060657664

what's this about?

cc @visionmedia

**Comment by tj** [comment]
my benchmarks is pretty contrived but im doing 1000 messages per tick in this case. I initially figured node would wrap things up in iovecs but even doing some crappy custom batching really speeds things up, for larger messages it's slower since I have to copy though, definitely not idea. I might have time to look at it more today but here's the benchmark scripts:

https://github.com/visionmedia/super-sockets/blob/master/benchmark/pub.js
https://github.com/visionmedia/super-sockets/blob/master/benchmark/sub.js

and my lame batch mechanism:

https://github.com/visionmedia/super-sockets/blob/master/lib/batch.js

the logic right now is pretty ad-hoc too, no limiting on batch sizing etc, I'm just batching 10 messages or the ttl of 100ms but obviously libuv couldn't make assumptions like that.

https://github.com/visionmedia/super-sockets/blob/master/lib/sockets/pub.js#L37

![](http://f.cl.ly/items/0E3u3u2p0P0T2z0T461W/Screen%20Shot%202012-07-15%20at%2012.05.53%20AM.png)

**Comment by bnoordhuis** [comment]
> libuv writes iovec's right?

Only if you pass multiple uv_buf_t structs to uv_write(). Node never does that, though.

**Comment by tj** [comment]
ah ok thanks. I should have specified the node part in the tweet

**Comment by bnoordhuis** [comment]
Continues in joyent/node#3714.
