### ISSUE TITLE
test wanted: oio_* methods should fail if req param hasn't been initialized

### ISSUE THREAD

**Issue by ry** [joyent/libuv#5]
Should oio_req need to be initialized before each use? Currently in Linux  this is necessary.

**Comment by piscisaureus** [comment]
I don't care. If it makes your life easy, we can do this.
We shouldn't _guarantee_ that oio_\* failes if oio_req is uninitialized. It is difficult to check, because the user allocates oio_req memory himself -- (oio_req->flags & OIO_REQ_INITIALIZED) might be true even if oio_req_init was never called.

**Comment by ry** [comment]
agreed. it's up to us to have asserts on each implementation. closing.
