### ISSUE TITLE
Compilation error because of rwlock.

### ISSUE THREAD

**Issue by meh** [joyent/libuv#551]
```
vendor/libuv/include/uv-private/uv-unix.h:102:1: error: unknown type name ‘pthread_rwlock_t’
```

I'm getting this error, with glibc 2.16.0, Arch Linux and `Linux 3.5.3-zen-00489-g2332dad #2 ZEN SMP PREEMPT`.

Apparently rwlocks are enabled only if:

``` c
#if defined __USE_UNIX98 || defined __USE_XOPEN2K
```

Defining one of the two before including `pthread.h` solves the issue, dunno which path you want to take.

EDIT: I found the real culprit, compiling with `-std=c99` disables one of those two, using `-std=gnu99` solves the issue too.

**Comment by bnoordhuis** [comment]
Does that happen when you compile libuv itself or when you're compiling something that uses libuv headers?

**Comment by meh** [comment]
When compiling something that uses the header.

I realize now the issue was misleading, sorry about that.

**Comment by meh** [comment]
Now that I think of it, it's probably `_GNU_SOURCE` missing from `uv.h`, it's defined when compiling libuv but missing in the header.

**Comment by bnoordhuis** [comment]
Okay, that's not really a libuv bug, you'll just have to make sure that you compile with the right flags. If you use gyp, that is all taken care of. If you compile with autotools, add a AC_GNU_SOURCE to your configure.ac.

I don't want to add a `#define _GNU_SOURCE` in uv.h because it a) won't work if uv.h is not the first include, and b) changes the compilation environment, i.e. it "leaks".

**Comment by meh** [comment]
Agree, it was just unexpected, it could maybe be added to the documentation.

**Comment by bnoordhuis** [comment]
I've added a note in 2b04bc7.
