### ISSUE TITLE
assertion failed in benchmark-muti-accept.c  on line 123

### ISSUE THREAD

**Issue by sunnyboy00** [joyent/libuv#602]
assertion failed in benchmark-muti-accept.c  on line 123,

assertion failed in benchmark-udp-pummel.c  on line 98

assertion failed in asynl.c  on line 77

windows 7, visual studio 2008.

**Comment by vtudose** [comment]
The benchmark benchmark-muti-accept.c fails because the **pending_ipc_info.socket_info** field is unitialized. This is the responsable code in file **pipe.c** function **uv_pipe_accept:725**

``` C
if (server->ipc) {
    if (!server->pending_ipc_info.socket_info) {
      /* No valid pending sockets. */
      uv__set_sys_error(loop, WSAEWOULDBLOCK);
      return -1;
    }
```

The **pending_ipc_info.socket_info** field gets initialized in function **uv_process_pipe_read_req** (file **pipe.c:1277**)  but that function never gets called.

**Comment by paulbombarde** [comment]
I still have the "assertion failed in benchmark-multi-accept.c on line 123" on my windows 10 machine. As far as I can see the analysis done by vtudose is still valid, a least on branch v1.x. [edit: I just check : the benchmark-multi-accept is also ko on master].

From #926, some work has been done on this, but the benchmark-multi-accept is still ok. Any news on this side ?

**Comment by saghul** [comment]
Please go to libuv/libuv, that's were current development happens, this repo is dead.
