### ISSUE TITLE
uv_write_start/uv_write_stop

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#634]
These methods would allow the write queue of streams to be paused and resumed.
Once a stream is created, the stream is writing automatically and has to be stopped with uv_write_stop after creation in order to utilize this effect.
This would ensure API compatibility.

This would put libuv functionality on par with libev functionalywise.

**Comment by bnoordhuis** [comment]
It was discussed recently in #libuv (I don't remember if it was with you or @creationix).

I personally don't see the need for such functions. uv_read_stop() is necessary because you don't control incoming data. That argument doesn't hold for uv_write_stop() because your application controls when it calls uv_write().

We'd also need to devise a mechanism to convey how many bytes have already been sent out by the time uv_write_stop() was called. Applications would almost certainly need that information.

Apart from that, I believe it may be hard - bordering on impossible - to implement well on Windows: when you call uv_write(), the data is immediately handed off to the operating system. Cancelling outstanding requests is apparently tricky business.

@piscisaureus WDYT?

**Comment by txdv** [comment]
It was me.
On unix it is also true that it immediately tries to hand the data of to the OS(I took a look at the implementation).
But there is still a queue, you can turn of the IO watchers, buffer all the data in the queue and wait for a write_start.
Well, I will wait for @piscisaureus answer as well.

**Comment by bnoordhuis** [comment]
> On unix it is also true that it immediately tries to hand the data of to the OS(I took a look at the implementation).

That's not quite the same thing. On Unices, we try to do the write immediately. If it works, happy joy. If it fails, we wait for the socket to become writeable and try again.

The IOCP approach is different. You hand off the data to to the kernel and it starts sending it at its leisure. You won't hear from the kernel again until all data has been sent or an error occurs.

When you call uv_write_stop(), libuv would need to cancel the IOCP request but apparently that's hard (or impossible) to do reliably.

**Comment by piscisaureus** [comment]
I see absolutely no point in uv_write_stop. Can you come up with an actual use case where you'd need this?

**Comment by txdv** [comment]
There is a lib for C#/mono written which supports the write_read/stop which is based on libev that supports this behaviour. libuv was supposed to be a backend for this lib.
@piscisaureus the sufficient argument for me to drop this entire idea is if it is really that hard to implement on windows(as bnoordhuis described it).

**Comment by piscisaureus** [comment]
@txdv well it _is_ hard to implement on windows :-)

But, what is the name of that c# lib? I'd be quite curious, because I honestly cannot think of a single use case, so I would like to look at the API this lib offers.

**Comment by txdv** [comment]
https://github.com/jacksonh/manos
