### ISSUE TITLE
Win 32: SSIZE_T redefined

### ISSUE THREAD

**Issue by jdduncan** [joyent/libuv#702]
I have a node module that builds successfully on 64-bit Windows but fails to build on 32-bit Windows. 

C:\Program Files\Microsoft SDKs\Windows\v7.0A\include\basetsd.h line 422 says:
typedef LONG_PTR SSIZE_T, *PSSIZE_T;

But $HOME/.node-gyp/0.8.19/deps/uv/include/uv-private/uv-win.h line 27 says:
 typedef intptr_t ssize_t;

So the compiler gives error C2371, redefinition of SSIZE_T with different basic types.

uv-win.h checks for _SSIZE_T_ and _SSIZE_T_DEFINED, but I don't see where these are defined other than in uv-win.h itself.

I can force the 32-bit build to work if I edit uv-private/uv-win.h to say:
  typedef LONG_PTR ssize_t

**Comment by piscisaureus** [comment]
Which msvc version are you using? We had to add that typedef because msvc (at least up to vs2010) didn't define `ssize_t`. The `SSIZE_T` and `_SSIZE_T_DEFINED` are just heuristics, it's common to define one of these macros when `ssize_t` is supported or shimmed but not a guarantee.

By the way, I don't really see what the definition of `SSIZE_T` in the windows SDK has to do with it. Apparently the `LONG_PTR` type eventually evaluates to the same basic type as `ssize_t`, but I can't really see how that's more than just a coincidence.

**Comment by jdduncan** [comment]
A C identifier should be case-sensitive ... and yet the compiler is clearly telling me that typedef ssize_t on line 27 of uv-win.h is a redefinition of typedef SSIZE_T on line 422 of basetsd.h.
This is VS 2010.

**Comment by piscisaureus** [comment]
So probably you will want to find the line `#define ssize_t SSIZE_T` :-)

**Comment by jdduncan** [comment]
Yes, we found this errant #define in some older library code and were able to remove it.  This resolves the issue for me.

**Comment by bnoordhuis** [comment]
Great, closing.
