### ISSUE TITLE
unix, windows: make uv_run() re-entrant?

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#758]
I ran into this while trying to write bindings for Chicken Scheme.

Chicken Scheme uses a somewhat esoteric approach to garbage collection called 'Cheney on the MTA'. It compiles Scheme code to CPS C code, meaning functions never return, and cleans up the stack whenever it threatens to overflow. (It's essentially bi-generational GC with the stack as the new object space and the heap as the old object space.)

What that means is that a libuv callback can call into the Scheme run-time only once because the Scheme code never returns.

In uv-unix, making uv_run() re-entrant requires little effort, can be done at little to no run-time cost and will probably result in code deduplication.

**Comment by piscisaureus** [comment]
I think in the past we flamed someone for making a request like this (it was about libuv's intolerance for people that call longjmp() from a callback).

As I read it, this problem is the same. I think making libuv reentrant like that will in fact be very hard. You'd have to assume that no callback would ever return, so there can be absolutely no logic after the callback invocation.. [This](https://github.com/joyent/libuv/blob/c43e8516b105b8bcbbd0a2d591dd1e520bb22357/src/unix/stream.c#L540-L553) for example, would have to change.
