### ISSUE TITLE
Multiple loops?

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#83]
Are there any plans to add multiple loop support?
I know node is all about one process, one event loop, but there are other projects which support more then 1 event loop.

**Comment by piscisaureus** [comment]
There are plans but we're not sure yet what the api will look like.

**Comment by ry** [comment]
The branch is https://github.com/joyent/libuv/tree/multiplicity

The question is:

Do we want to have independent event loops for each thread?
OR
Do we want to have a thread pool handle events like IOCP?

**Comment by txdv** [comment]
I don't understand the question, since I'm not quite familiar with IOCP.

Could you give a more detailed explanation?
API showcases would help to understand.

**Comment by rmustacc** [comment]
Ultimately you need to support both methods because each one solves different problems.

The IOCP model basically lets you multiple dispatch for a single event loop. i.e. you would have multiple threads that each called port_get(), but a given fd would ideally only be serviced by one thread at a time. The API could conceivably look the same as what you already have, but you specify a number of threads to service your event loop.

However, other consumers do need entirely separate event loops. The two models are orthogonal.

**Comment by ry** [comment]
@rmustacc makes a good point. Both models are beneficial. 

To make this more concrete, let's consider how Node.js goes multicore. Our current method involves using ancillary messages over a unix pipe to send a server file descriptor to other Node proceses. Each of the Nodes polls for readability on that server fd and accepts greedily. This is the Nginx model as well. It has the effect of load balancing incoming connections across each of the processes. Libraries like http://learnboost.github.com/cluster/ ease the setup of this for users.

How will we do this on Windows? It is possible to send a file descriptor to another process in Windows but the OS does not allow sockets to be associated with more than one IOCP. The traditional Unix model falls apart. As I see it there are two possible solutions
1. Using V8 Isolates we put all of the various Node instances inside the same process, each in their own thread. We use a single IOCP across all of the Nodes. There are several important unanswered questions that need to be considered before going down this path. For example: we won't have control over which thread a callback is dispatched to. It may be that a callback is dispatched to a thread who is running a Node instance not associated with that callback. How do we dispatch that event to the correct Node?
2. Continue using a whole process for each Node instance each with their own IOCP. Use a thread with a small select loop to poll for readability on server handles. (The idea being that you never have many server handles.) Marshal accept events from the select-loop-thread back into the main thread via `uv_async_send` (or some other mechanism).

**Comment by DrPizza** [comment]
Option 1 is certainly the more Windowsy way of doing things.

Maybe I'm misunderstanding the problem, and/or maybe this is more complicated than you would like, but I would think a neat enough solution to the "dispatch to the right instance" problem could be constructed something like this.

Make a two-tier system; have an IOCP with its own thread per Node instance, and a single top-level IOCP. All handles/sockets get associated with the top-level IOCP, and all use the completion key to identify which Node instance they belong to. An obvious candidate for the completion key would be the second-level IOCP itself. I know currently you use the completion key to store the socket handle, but you never actually use that value anyway.

The top-level IOCP dequeues completion requests, picks the right instance IOCP (based on the completion key) and then enqueues each request into the correct target IOCP. The target IOCP then just carries on as normal.

**Comment by txdv** [comment]
Manos, the C# cousin of node.js, would be happy about option 1, though, as already mentioned, both models should make it into the lib :)

**Comment by piscisaureus** [comment]
@ry's first model is a total misfit for node, because all i/o is tied to the v8 isolate and the thread that initiated the i/o. The one iocp per event loop / thread is by far the best solution for this problem imho. There are numerous ways to solve the special problem of prefork server - a select thread, overlapped io w/ events instead of an iocp, WSAEventSelect etc.

We probably don't need the second model for node either, I don't see node switching from a multiprocess architecture to a multithreaded architecture in the near future. But we can support the second model just because it helps other projects - it's fairly easy to implement and other event loops support it as well.

**Comment by piscisaureus** [comment]
If people are really interested in model one, please help us specify what the semantics would be; what should be the semantics of uv_idle, how would locking work for you, how can we ensure that concurrent access doesn't clobber libuv's internal state?

**Comment by txdv** [comment]
Maybe it might be a misfit for node, but node doesn't have to use that functionality at all.
Node doesn't have to provide all the functionality provided by libuv.

**Comment by ry** [comment]
multiple loops supported in e3f910d0a9dc523565b9f7437079e0db45926b7f

**Comment by txdv** [comment]
On what branch is this candy?

**Comment by ry** [comment]
master
