### ISSUE TITLE
Integrate FS operations into uv_write?

### ISSUE THREAD

**Issue by Keno** [joyent/libuv#839]
The filesystem operations being so separate in the current implementation is a little unfortunate. It would be nice if writing to files could be integrated with the rest of the libuv I/O types to provide a more uniform interface. There is of course the issue that unlike the other types of I/O, files support positional writes whereas the other types of I/O do not. Discussing this with @bnoordhuis on IRC, one solution might be to have `uv_pwrite` for files that at least uses the same API and callback structure. 

/cc @vtjnash

**Comment by vtjnash** [comment]
Is it crazy to think that the exact same uv_write call should be usable for file handles? The harder issue that I see is with synchronizing reads and writes. If I want file-like access then it makes sense to me to use the existing file API.

(edit: deleted text "It seems that you just fixed the julia issue with this anyways" since it only applies to loladiro and doesn't make sense in this context)

**Comment by saghul** [comment]
I wouldn't object exporing the possibility of creating some "fs_stream" handle, which would use the majority of the stream functions, but as it stands we cannot merge the functionality, we need a new handle for that.

Please open an RFC/issue at libuv/libuv if this is still something you'd like to see / work on.

PS: I'm really sorry for the huge delay...
