### ISSUE TITLE
build: Upgrade to OS X Mavericks broke --disable-dtrace

### ISSUE THREAD

**Issue by rurban** [joyent/libuv#963]
Without `--disable-dtrace` it compiles and tests okay.
Since my upgrade to teh latest OSX, with `--disable-dtrace` the command DTRACE is empty and executing -h -xnolibs ... is causing an error.

**Comment by jneu** [comment]
I was able to reproduce this on OS X Mavericks with the following steps:
1. ./configure
2. make
3. make clean
4. ./configure --disable-dtrace
5. make
I don't think this issue is specific to any particular version of OS X, though.

Essentially the issue is this:
1. The initial make creates dependency files in the src/unix/.deps directory. These are not cleaned up by the make clean.
2. The second configure adds rules to make uv-dtrace.h, even though it's not added as a BUILT_SOURCES.
3. Since uv-dtrace.h is found in the dependency files, the second make causes it's recipe to run.
4. The recipe for uv-dtrace.h fails because it's incomplete (since --disable-dtrace was added).

To fix it, I added conditionals around the uv-dtrace.h rules in Makefile.am so they are not added to the Makefile if dtrace is not configured.
